name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  style:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dprint/check@v1.2

  lint:
    name: Lint codebase using clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy

      - name: Check no warnings
        uses: actions-rs/clippy@master
        with:
          args: --all-features --all-targets -- -D warnings

  tests:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        args: [
            '',
            '--all-features',
            '--manifest-path=lib/Cargo.toml --no-default-features',
            '--manifest-path=macro/Cargo.toml --no-default-features',
            '--manifest-path=lib/Cargo.toml --features=all-backends' # test all backends without logging
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: Swatinem/rust-cache@v1.2.0
        with:
          key: "${{ matrix.args }}"

      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.args }}

  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1.2.0

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: rustdoc
          args: --manifest-path=lib/Cargo.toml -- -D broken_intra_doc_links
